### ISSUE TITLE
[FEATURE] Implement ChatCompletition Api

### ISSUE THREAD

**Issue by thespino** [thespino/odoogpt#40]
### Todo 

- [x] Setting to select which type of api using: 
  - [x] Completitions 
  - [x] ChatCompletitions 
- [x] When ChatCompletitions is selected, use a special field for the first system message instead of the prefix
- [x] Mark the prefix way as "deprecating", push to use the ChatCompletition api. 
- [x] Implement ChatCompletitions in utils 
- [x] Use the selected option 
- [x] Check openai python module version to prevent stupid errors. Since v0.27.0

Refer to: 
https://www.youtube.com/watch?v=e2uvhJ7r1UQ 
https://platform.openai.com/docs/guides/chat 

----

### Then  

- [ ] UPDATE DOCS
